# 미국 주식(섹터) 후보 — app.py / usa_export_core 공통 (기존 app.py CANDIDATES 정리, ARM 중복 제거)
CANDIDATES = {
    "NVDA": ["NVIDIA", "Semiconductors"],
    "AVGO": ["Broadcom", "Semiconductors"],
    "AMD": ["AMD", "Semiconductors"],
    "INTC": ["Intel", "Semiconductors"],
    "MU": ["Micron", "Semiconductors"],
    "TSM": ["TSMC", "Semiconductors"],
    "ARM": ["ARM Holdings", "Semiconductors"],
    "AMAT": ["Applied Materials", "Semiconductors"],
    "LRCX": ["Lam Research", "Semiconductors"],
    "KLAC": ["KLA Corp", "Semiconductors"],
    "ASML": ["ASML Holding", "Semiconductors"],
    "TXN": ["Texas Instr.", "Semiconductors"],
    "QCOM": ["Qualcomm", "Semiconductors"],
    "ADI": ["Analog Devices", "Semiconductors"],
    "MRVL": ["Marvell Tech", "Semiconductors"],
    "MPWR": ["Monolithic Power", "Semiconductors"],
    "TER": ["Teradyne", "Semiconductors"],
    "MSFT": ["Microsoft", "Information Technology"],
    "AAPL": ["Apple", "Information Technology"],
    "ORCL": ["Oracle", "Information Technology"],
    "CRM": ["Salesforce", "Information Technology"],
    "ADBE": ["Adobe", "Information Technology"],
    "NOW": ["ServiceNow", "Information Technology"],
    "IBM": ["IBM", "Information Technology"],
    "INTU": ["Intuit", "Information Technology"],
    "PANW": ["Palo Alto Networks", "Information Technology"],
    "PLTR": ["Palantir Tech", "Information Technology"],
    "SNOW": ["Snowflake", "Information Technology"],
    "WDAY": ["Workday", "Information Technology"],
    "CDNS": ["Cadence Design", "Information Technology"],
    "GOOGL": ["Alphabet", "Communication"],
    "META": ["Meta", "Communication"],
    "NFLX": ["Netflix", "Communication"],
    "TMUS": ["T-Mobile", "Communication"],
    "DIS": ["Disney", "Communication"],
    "VZ": ["Verizon", "Communication"],
    "CMCSA": ["Comcast", "Communication"],
    "AMZN": ["Amazon", "Consumer Disc."],
    "TSLA": ["Tesla", "Consumer Disc."],
    "COST": ["Costco", "Consumer Disc."],
    "WMT": ["Walmart", "Consumer Disc."],
    "HD": ["Home Depot", "Consumer Disc."],
    "LOW": ["Lowe's", "Consumer Disc."],
    "TJX": ["TJX Companies", "Consumer Disc."],
    "NKE": ["Nike", "Consumer Disc."],
    "BKNG": ["Booking Holdings", "Consumer Disc."],
    "SBUX": ["Starbucks", "Consumer Disc."],
    "MCD": ["McDonald's", "Consumer Disc."],
    "PEP": ["PepsiCo", "Consumer Disc."],
    "JPM": ["JPMorgan", "Financials"],
    "V": ["Visa", "Financials"],
    "MA": ["Mastercard", "Financials"],
    "GS": ["Goldman Sachs", "Financials"],
    "BAC": ["Bank of America", "Financials"],
    "MS": ["Morgan Stanley", "Financials"],
    "AXP": ["American Express", "Financials"],
    "BRK-B": ["Berkshire Hathaway", "Financials"],
    "BLK": ["BlackRock", "Financials"],
    "SPGI": ["S&P Global", "Financials"],
    "LLY": ["Eli Lilly", "Health Care"],
    "UNH": ["UnitedHealth", "Health Care"],
    "ABBV": ["AbbVie", "Health Care"],
    "MRK": ["Merck", "Health Care"],
    "JNJ": ["J&J", "Health Care"],
    "ISRG": ["Intuitive Surgical", "Health Care"],
    "AMGN": ["Amgen", "Health Care"],
    "PFE": ["Pfizer", "Health Care"],
    "TMO": ["Thermo Fisher", "Health Care"],
    "VRTX": ["Vertex Pharma", "Health Care"],
    "GE": ["GE Aerospace", "Industrials"],
    "CAT": ["Caterpillar", "Industrials"],
    "RTX": ["RTX Corp", "Industrials"],
    "HON": ["Honeywell", "Industrials"],
    "UPS": ["UPS", "Industrials"],
    "LMT": ["Lockheed Martin", "Industrials"],
    "XOM": ["Exxon Mobil", "Energy"],
    "CVX": ["Chevron", "Energy"],
    "NEE": ["NextEra Energy", "Utilities"],
    "LIN": ["Linde", "Materials"],
    "VRT": ["Vertiv Holdings", "Industrials"],
    "ANET": ["Arista Networks", "Information Technology"],
    "UBER": ["Uber Technologies", "CASH"],
    "MDB": ["MongoDB", "Information Technology"],
    "CRWD": ["CrowdStrike", "Information Technology"],
    "NVO": ["Novo Nordisk", "Health Care"],
    "CELH": ["Celsius Holdings", "Consumer Staples"],
    "DE": ["Deere & Co", "Industrials"],
    "KKR": ["KKR & Co.", "Financials"],
    "CB": ["Chubb Limited", "Financials"],
}
